# Generated by Django 4.2.6 on 2023-11-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livromodel',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='autor',
            field=models.CharField(default=11, max_length=200, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livromodel',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='num_pag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='editora',
            field=models.CharField(max_length=200, verbose_name='Editora'),
        ),
    ]
